apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bind-route
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
    - name: queueName
      value: hello
    - name: host
      value: amqp://admin:admin@localhost:31572
    - name: durable
      value: true
    - name: deleteWhenUnused
      value: false
    - name: ttlInSeconds
      value: 60
    - name: prefetchCount
      value: 0
    - name: exclusive
      value: false
    - name: maxPriority
      value: 5